name: New Action Benchmark

on:
  push:
    branches: [main, dev/**]

  workflow_dispatch:
    inputs:
        version:
          description: 'new action version:'
          required: false
          default: 'latest'

jobs:
  module-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Run Benchmark
        run: MODERN_VERSION=${{ github.event.inputs.branch }} node ./scripts/new-action.js
  
      - name: Create or Update Comment
        uses: peter-evans/create-or-update-comment@v4.0.0
        with:
          issue-number: 1
          body: |
            version: 1.0.0

