name: Upgrade Action Benchmark

on:
  workflow_dispatch:
    inputs:
        version:
          description: 'Upgrade action version:'
          required: true
          default: 'latest'

jobs:
  upgrade-action-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
    
      - name: Install Pnpm
        run: npm i -g pnpm

      - name: Run Script
        run: MODERN_VERSION=${{ github.event.inputs.version || 'latest' }} node ./scripts/upgrade.mjs
  
      - name: Create or Update Comment
        uses: peter-evans/create-or-update-comment@v4.0.0
        with:
          token: ${{ secrets.CI_TOKEN }}
          issue-number: 4
          body-path: 'result.md'

