name: New Action Benchmark

on:
  workflow_dispatch:
    inputs:
        version:
          description: 'new action version:'
          required: true
          default: 'latest'

jobs:
  new-action-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
  
      - name: Create or Update Comment
        uses: peter-evans/create-or-update-comment@v4.0.0
        with:
          token: ${{ secrets.CI_TOKEN }}
          issue-number: 3
          body: 'test'

